# Site settings
title: RBE/CS549 Computer Vision
description: "Course materials and notes for Worcester Polytechnic Institute's class RBE/CS549: Computer Vision."
baseurl: ""
url: "http://rbe549.github.io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge


theme: jekyll-theme-cayman