# Site settings
title: PeAR WPI Teaching
description: "Course materials and notes for Worcester Polytechnic Institute's classes taught by the PeAR Group."
baseurl: ""
url: "http://rbe549.github.io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge


theme: jekyll-theme-cayman